name: CI - Build All Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  accounting-service:
    name: Build Accounting Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          
      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
              <servers>
                  <server>
                      <id>github</id>
                      <username>${{secrets.GITHUB_ACTOR}}</username>
                      <password>${{secrets.GITHUB_TOKEN}}</password>
                  </server>
              </servers>
          </settings>
          EOF

      - name: Build and Deploy Accounting Service
        run: mvn clean deploy -DskipTests -s ~/.m2/settings.xml
        working-directory: accounting-service

  asset-management-service:
    name: Build Asset Management Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
              <servers>
                  <server>
                      <id>github</id>
                      <username>${{secrets.GITHUB_ACTOR}}</username>
                      <password>${{secrets.GITHUB_TOKEN}}</password>
                  </server>
              </servers>
          </settings>
          EOF

      - name: Build and Deploy Accounting Service
        run: mvn clean deploy -DskipTests -s ~/.m2/settings.xml
        working-directory: accounting-service

  resource-administration-service:
    name: Build Resource Administration Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
              <servers>
                  <server>
                      <id>github</id>
                      <username>${{secrets.GITHUB_ACTOR}}</username>
                      <password>${{secrets.GITHUB_TOKEN}}</password>
                  </server>
              </servers>
          </settings>
          EOF

      - name: Build and Deploy Accounting Service
        run: mvn clean deploy -DskipTests -s ~/.m2/settings.xml
        working-directory: accounting-service

  user-management-service:
    name: Build User Management Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
              <servers>
                  <server>
                      <id>github</id>
                      <username>${{secrets.GITHUB_ACTOR}}</username>
                      <password>${{secrets.GITHUB_TOKEN}}</password>
                  </server>
              </servers>
          </settings>
          EOF

      - name: Build and Deploy Accounting Service
        run: mvn clean deploy -DskipTests -s ~/.m2/settings.xml
        working-directory: accounting-service

